### ISSUE TITLE
[TODO] Make the installer use an openJDK version that doesnt suck.

### ISSUE THREAD

**Issue by HAV0X1014** [HAV0X1014/Pingbypass-Installer#1]

**Comment by HAV0X1014** [comment]
openlogic and temurin both fail running mc/earth

**Comment by HAV0X1014** [comment]
temurin works on my arch VM and ubuntu VM... no idea how or why it doesnt work on my VPSes running ubuntu 22.04

**Comment by ghost** [comment]
Try using Azul java, works perfectly for me on all my machines.

**Comment by HAV0X1014** [comment]
i'll try azul soon, thanks for letting me know about it

**Comment by HAV0X1014** [comment]
the issue is that the JDK versions dont include any fonts in them, which is what is causing the crash. The only workaround I can think of would be to include a step in the installer to install the fonts, but im not sure how that would work on all distros

**Comment by HAV0X1014** [comment]
going to try corretto as my last option, and if that still doesnt work, i'll use the official JDK

**Comment by HAV0X1014** [comment]
#2
